project:
  type: website
  output-dir: docs

website:
  title: Sejal's Website 
  navbar:
    left:
      - href: index.qmd
        text: Home
      - walkthrough.qmd
      - assignment_chartsmaps_yournamehere.qmd
      
  page-footer: 
    left: "Copyright 2022, Sejal Govindarao" 
    right: 
      - icon: github
        href: https://github.com/sejalgovindarao
      - icon: twitter 
        href: https://mobile.twitter.com/sejalg_

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true




